# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          'eu.gcr.io/whyse-staging/whyse-build-agent:$(tag)'
        arguments: -t eu.gcr.io/whyse-staging/whyse-build-agent:$(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'WhyseStagingDockerRegistry'
        repository: 'whyse-staging/whyse-build-agent'
        command: 'push'
        tags: '$(tag)'